"""create tables

Revision ID: a50cde241c4b
Revises: d7fd240a3cae
Create Date: 2023-05-01 11:46:52.766875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50cde241c4b'
down_revision = 'd7fd240a3cae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baked_goods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bakeries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bakeries')
    op.drop_table('baked_goods')
    # ### end Alembic commands ###
